-- The multi-tenant migration renamed orders.assigned_tailor_id to employee_id,
-- but the application code (CreateOrderForm, OrderEditForm, orders actions,
-- analytics, employees) was carried over unchanged and still writes/reads
-- assigned_tailor_id, so every order create/update fails with
-- "Could not find the 'assigned_tailor_id' column of 'orders' in the schema cache".
-- Renaming back restores the original gloriaz-daughter column name the app expects.

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'orders' AND column_name = 'employee_id'
  ) THEN
    ALTER TABLE public.orders RENAME COLUMN employee_id TO assigned_tailor_id;
  END IF;
END $$;

-- Constraint name is auto-generated by Postgres from the original column name;
-- rename defensively in case it differs from the expected default.
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'orders_employee_id_fkey'
  ) THEN
    ALTER TABLE public.orders RENAME CONSTRAINT orders_employee_id_fkey TO orders_assigned_tailor_id_fkey;
  END IF;
END $$;
